name: mass_refactor
description: A CLI tool for performing mass refactoring of files and folders.
version: 1.0.1
homepage: https://kakzaki.dev

environment:
  sdk: '>=2.14.0 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  mass_refactor:
