name: mass_refactor
description: A CLI tool for performing mass refactoring of files and folders.
version: 1.0.0
homepage: https://kakzaki.dev

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
